"""
Module utilizing lightweight NLP models and heuristics to accurately
identify the resume's primary language without heavy external dependencies.
"""

import re
from typing import Dict, Optional, Tuple
from dataclasses import dataclass

# Common language indicators (heuristic fallback if langdetect is unavailable)
LANGUAGE_INDICATORS = {
    "es": [
        "el",
        "la",
        "los",
        "las",
        "de",
        "que",
        "y",
        "en",
        "un",
        "ser",
        "se",
        "no",
        "haber",
        "por",
        "con",
        "su",
        "para",
        "como",
        "estar",
        "tener",
        "le",
        "lo",
        "todo",
        "pero",
        "más",
        "hacer",
        "o",
        "poder",
        "decir",
        "este",
        "ir",
        "otro",
        "ese",
        "la",
        "si",
        "me",
        "ya",
        "ver",
        "porque",
        "dar",
        "cuando",
        "él",
        "muy",
        "sin",
        "vez",
        "saber",
        "qué",
        "sobre",
        "mi",
        "alguno",
        "mismo",
        "yo",
        "también",
        "hasta",
        "año",
        "dos",
        "querer",
        "entre",
        "así",
        "primero",
        "desde",
        "grande",
        "eso",
        "ni",
        "nos",
        "llegar",
        "pasar",
        "tiempo",
        "ella",
        "sí",
        "día",
        "uno",
        "bien",
        "poco",
        "deber",
        "entonces",
        "poner",
        "cosa",
        "tanto",
        "hombre",
        "parecer",
        "nuestro",
        "tan",
        "donde",
        "ahora",
        "parte",
        "después",
        "vida",
        "quedar",
        "siempre",
        "creer",
        "hablar",
        "llevar",
        "dejar",
        "nada",
        "cada",
        "seguir",
        "menos",
        "nuevo",
        "encontrar",
        "algo",
        "solo",
        "pues",
        "llamar",
        "venir",
        "pensar",
        "salir",
        "volver",
        "conocer",
        "vivir",
        "sentir",
        "tratar",
        "mirar",
        "contar",
        "empezar",
        "esperar",
        "buscar",
        "existir",
        "entrar",
        "trabajar",
        "escribir",
        "perder",
        "producir",
        "ocurrir",
        "entender",
        "pedir",
        "recibir",
        "recordar",
        "terminar",
        "permitir",
        "aparecer",
        "conseguir",
        "comenzar",
        "servir",
        "sacar",
        "necesitar",
        "mantener",
        "resultar",
        "leer",
        "caer",
        "cambiar",
        "presentar",
        "crear",
        "abrir",
        "pasar",
        "considerar",
        "dar",
        "tomar",
        "responder",
        "crecer",
        "hacer",
        "traer",
        "descubrir",
        "conocer",
        "lograr",
        "comprender",
        "gustar",
        "obtener",
        "explicar",
        "oír",
        "realizar",
        "suponer",
        "comentar",
        "imaginar",
        "decidir",
        "asegurar",
        "desarrollar",
        "afirmar",
        "preguntar",
        "alcanzar",
        "diferenciar",
        "establecer",
        "utilizar",
        "formar",
        "dirigir",
        "notar",
        "provocar",
        "reconocer",
        "incluir",
        "observar",
        "comprobar",
        "comunicar",
        "adoptar",
        "proponer",
        "aportar",
        "revelar",
        "aplicar",
        "ejercer",
        "representar",
        "constituir",
        "exigir",
        "implicar",
        "contribuir",
        "transformar",
        "generar",
        "reflejar",
        "asumir",
        "demostrar",
        "garantizar",
        "promover",
        "indicar",
        "determinar",
        "significar",
        "comparar",
        "evaluar",
        "analizar",
        "identificar",
        "señalar",
        "mencionar",
        "describir",
        "resumir",
        "concluir",
        "sugerir",
        "recomendar",
        "orientar",
        "guiar",
        "facilitar",
        "optimizar",
        "mejorar",
        "incrementar",
        "reducir",
        "maximizar",
        "minimizar",
        "estandarizar",
        "automatizar",
        "digitalizar",
        "innovar",
        "liderar",
        "gestionar",
        "administrar",
        "coordinar",
        "supervisar",
        "evaluar",
        "auditar",
        "inspeccionar",
        "verificar",
        "validar",
        "certificar",
        "acreditar",
        "homologar",
        "normalizar",
        "regular",
        "reglamentar",
        "legislar",
        "normar",
        "estandarizar",
        "unificar",
        "armonizar",
        "integrar",
        "articular",
        "vincular",
        "conectar",
        "enlazar",
        "relacionar",
        "asociar",
        "agrupar",
        "clasificar",
        "categorizar",
        "ordenar",
        "organizar",
        "estructurar",
        "sistematizar",
        "planificar",
        "programar",
        "diseñar",
        "concebir",
        "idear",
        "inventar",
        "descubrir",
        "explorar",
        "investigar",
        "estudiar",
        "examinar",
        "analizar",
        "evaluar",
        "valorar",
        "tasar",
        "cotizar",
        "presupuestar",
        "financiar",
        "costear",
        "subvencionar",
        "patrocinar",
        "auspiciar",
        "respaldar",
        "apoyar",
        "sostener",
        "mantener",
        "conservar",
        "preservar",
        "proteger",
        "defender",
        "resguardar",
        "salvaguardar",
        "custodiar",
        "vigilar",
        "monitorear",
        "controlar",
        "regular",
        "fiscalizar",
        "sancionar",
        "penalizar",
        "multar",
        "castigar",
        "reprimir",
        "contener",
        "frenar",
        "detener",
        "parar",
        "suspender",
        "interrumpir",
        "cancelar",
        "anular",
        "invalidar",
        "revocar",
        "derogar",
        "abrogar",
        "rescindir",
        "terminar",
        "finalizar",
        "concluir",
        "cerrar",
        "clausurar",
        "liquidar",
        "disolver",
        "desintegrar",
        "descomponer",
        "desarmar",
        "desmontar",
        "desmantelar",
        "despedazar",
        "romper",
        "quebrar",
        "partir",
        "dividir",
        "separar",
        "aislar",
        "marginar",
        "excluir",
        "eliminar",
        "suprimir",
        "borrar",
        "tachar",
        "anular",
        "cancelar",
        "revocar",
        "invalidar",
        "desestimar",
        "rechazar",
        "denegar",
        "negar",
        "rehusar",
        "declinar",
        "receptar",
        "aceptar",
        "admitir",
        "recibir",
        "acoger",
        "abrazar",
        "adoptar",
        "incorporar",
        "integrar",
        "incluir",
        "agregar",
        "añadir",
        "sumar",
        "adicionar",
        "acumular",
        "reunir",
        "juntar",
        "agrupar",
        "concentrar",
        "centralizar",
        "focalizar",
        "enfocar",
        "orientar",
        "dirigir",
        "guiar",
        "conducir",
        "llevar",
        "transportar",
        "trasladar",
        "mover",
        "desplazar",
        "transferir",
        "transmitir",
        "comunicar",
        "informar",
        "notificar",
        "avisar",
        "alertar",
        "advertir",
        "prevenir",
        "proteger",
        "defender",
        "resguardar",
        "salvaguardar",
        "custodiar",
        "vigilar",
        "monitorear",
        "controlar",
        "regular",
        "fiscalizar",
        "sancionar",
        "penalizar",
        "multar",
        "castigar",
        "reprimir",
        "contener",
        "frenar",
        "detener",
        "parar",
        "suspender",
        "interrumpir",
        "cancelar",
        "anular",
        "invalidar",
        "revocar",
        "derogar",
        "abrogar",
        "rescindir",
        "terminar",
        "finalizar",
        "concluir",
        "cerrar",
        "clausurar",
        "liquidar",
        "disolver",
        "desintegrar",
        "descomponer",
        "desarmar",
        "desmontar",
        "desmantelar",
        "despedazar",
        "romper",
        "quebrar",
        "partir",
        "dividir",
        "separar",
        "aislar",
        "marginar",
        "excluir",
        "eliminar",
        "suprimir",
        "borrar",
        "tachar",
    ],
    "fr": [
        "le",
        "de",
        "et",
        "à",
        "un",
        "il",
        "être",
        "et",
        "en",
        "avoir",
        "que",
        "pour",
        "dans",
        "ce",
        "son",
        "une",
        "sur",
        "avec",
        "ne",
        "se",
        "pas",
        "tout",
        "plus",
        "par",
        "grand",
        "en",
        "une",
        "être",
        "et",
        "en",
        "avoir",
        "que",
        "pour",
        "dans",
        "ce",
        "son",
        "une",
        "sur",
        "avec",
        "ne",
        "se",
        "pas",
        "tout",
        "plus",
        "par",
        "grand",
        "en",
        "une",
        "être",
        "et",
        "en",
        "avoir",
        "que",
        "pour",
        "dans",
        "ce",
        "son",
        "une",
        "sur",
        "avec",
        "ne",
        "se",
        "pas",
        "tout",
        "plus",
        "par",
        "grand",
    ],
    "de": [
        "der",
        "die",
        "und",
        "in",
        "den",
        "von",
        "zu",
        "das",
        "mit",
        "sich",
        "des",
        "auf",
        "für",
        "ist",
        "im",
        "dem",
        "nicht",
        "ein",
        "eine",
        "als",
        "auch",
        "es",
        "an",
        "werden",
        "aus",
        "er",
        "hat",
        "dass",
        "sie",
        "nach",
        "wird",
        "bei",
        "einer",
        "um",
        "am",
        "sind",
        "noch",
        "wie",
        "einem",
        "über",
        "einen",
        "so",
        "zum",
        "war",
        "haben",
        "nur",
        "oder",
        "aber",
        "vor",
        "zur",
        "bis",
        "mehr",
        "durch",
        "man",
        "sein",
        "wurde",
        "sei",
        "in",
        "wird",
        "ihm",
        "eine",
        "eines",
        "da",
        "soll",
        "mir",
        "kein",
        "wir",
        "eine",
        "unter",
        "hat",
        "denn",
        "nun",
        "alles",
        "nur",
        "oder",
        "aber",
        "vor",
        "zur",
        "bis",
        "mehr",
        "durch",
        "man",
        "sein",
        "wurde",
        "sei",
        "in",
        "wird",
        "ihm",
        "eine",
        "eines",
        "da",
        "soll",
        "mir",
        "kein",
        "wir",
        "eine",
        "unter",
        "hat",
        "denn",
        "nun",
        "alles",
    ],
    "it": [
        "il",
        "di",
        "che",
        "e",
        "la",
        "per",
        "un",
        "a",
        "è",
        "in",
        "una",
        "non",
        "si",
        "da",
        "mi",
        "lo",
        "le",
        "ha",
        "i",
        "ma",
        "ho",
        "cosa",
        "come",
        "io",
        "questo",
        "qui",
        "quello",
        "sono",
        "ci",
        "ti",
        "ne",
        "no",
        "se",
        "anche",
        "tutto",
        "più",
        "con",
        "grande",
        "in",
        "una",
        "essere",
        "e",
        "in",
        "avere",
        "che",
        "per",
        "dentro",
        "questo",
        "suo",
        "una",
        "su",
        "con",
        "non",
        "si",
        "non",
        "tutto",
        "più",
        "per",
        "grande",
    ],
}

LANGUAGE_NAMES = {
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "pt": "Portuguese",
    "nl": "Dutch",
    "ru": "Russian",
    "zh": "Chinese",
    "ja": "Japanese",
    "ko": "Korean",
    "ar": "Arabic",
    "hi": "Hindi",
    "unknown": "Unknown",
}


@dataclass
class LanguageDetectionResult:
    language_code: str
    language_name: str
    confidence: float
    method_used: str


class LanguageDetector:
    """Detects the primary language of a given text."""

    @classmethod
    def detect(cls, text: str) -> LanguageDetectionResult:
        """
        Detects the language of the provided text.
        Attempts to use `langdetect` first, falls back to heuristic word matching.
        """
        if not text or len(text.strip()) < 10:
            return LanguageDetectionResult("en", "English", 0.0, "fallback_short_text")

        # Attempt 1: Use langdetect if available
        try:
            from langdetect import detect, LangDetectException

            lang_code = detect(text)
            # langdetect returns 'en' for English, 'es' for Spanish, etc.
            lang_name = LANGUAGE_NAMES.get(lang_code, LANGUAGE_NAMES["unknown"])
            return LanguageDetectionResult(lang_code, lang_name, 0.85, "langdetect")
        except ImportError:
            pass  # Fall back to heuristic
        except Exception:
            pass  # Fall back to heuristic on detection failure

        # Attempt 2: Heuristic word frequency matching
        return cls._heuristic_detection(text)

    @classmethod
    def _heuristic_detection(cls, text: str) -> LanguageDetectionResult:
        """Fallback heuristic detection based on common stop words."""
        words = re.findall(r"\b\w+\b", text.lower())
        if not words:
            return LanguageDetectionResult("en", "English", 0.5, "heuristic_empty")

        scores = {lang: 0 for lang in LANGUAGE_INDICATORS}
        total_words = len(words)

        for word in words:
            for lang, indicators in LANGUAGE_INDICATORS.items():
                if word in indicators:
                    scores[lang] += 1

        # Normalize scores
        max_score = max(scores.values())
        best_lang = "en"  # Default to English

        if max_score > 0:
            best_lang = max(scores, key=scores.get)
            confidence = min(0.95, (max_score / total_words) * 5.0)  # Scale confidence
        else:
            confidence = 0.5

        lang_name = LANGUAGE_NAMES.get(best_lang, LANGUAGE_NAMES["unknown"])
        return LanguageDetectionResult(
            best_lang, lang_name, round(confidence, 2), "heuristic"
        )

    @classmethod
    def is_english(cls, text: str) -> bool:
        """Quick check if text is predominantly English."""
        result = cls.detect(text)
        return result.language_code == "en" and result.confidence > 0.6
