 feature/document-semver-process-756
# Generated by Django 6.1 on 2026-08-24 07:43

# Generated by Django 6.1 on 2026-08-24 10:41
 main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0020_merge_20260824_0025"),
        ("analyzer", "0020_resumebadge"),
    ]

    operations = []
